### ISSUE TITLE
Feature proposal: class(es) per column

### ISSUE THREAD

**Issue by ronen** [crisward/riot-grid2#13]
I'd like to propose adding another entry to the `columns` object, allowing you to specify a class or classes that grid2 will set on each cell in that column.  The goal being to allow per-column css tweaking.  e.g. something like:

```javascript
var columns = [
    {label:'#',field:'id',width:50,fixed:true,class:"identifier"},
    {label:'name',field:"name1",width:120,fixed:true, class:"name primary"},
    {label:'name2',field:"name2",width:120,class: ["name", "secondary"]},
    {label:"popularity",field:"popularity",width:200,tag:"image-cell"}
]
```

As in the above example it would accept a string or array of strings with the class names.

I've got it working in my own copy of grid2 in a project i've been working on, whose source has diverged.  Want to check that you approve of the idea/see if you have any feedback or suggestions before I port it back.

**Comment by crisward** [comment]
Sounds cool. 
I'm assuming it hasn't had any performance implications? 
Also I'm guessing you're adding the class to the header tags too?

**Comment by ronen** [comment]
> Sounds cool.

great

> I'm assuming it hasn't had any performance implications?

Non-zero additional code, but I can't imagine it's significant.

> Also I'm guessing you're adding the class to the header tags too?

Yep

Just submitted PR
