### ISSUE TITLE
custom tags display broken when updating data

### ISSUE THREAD

**Issue by PascalLeMerrer** [crisward/riot-grid2#21]
Hello

I have a table in which the first column uses a custom tag as a renderer. it displays a progress bar.
I developed a feature to allow hiding/showing columns in the table. It updates the columns attribute of grid2.
I works when no custom tag is used for rendering.
But when I set a custom tag for rendering the first column, hiding a column have unpredictable effect. It tries to render some cells in other columns with the custom tag.

**Comment by crisward** [comment]
ok, sounds like the indexes are being cached between data updates.

Are you just modifying the underlying data? If so I'll try and add a test for this and make sure it does the right thing. 

Does it go wrong straightaway, or do you need to scroll to get the wrong tags?

**Comment by PascalLeMerrer** [comment]
We do not modify the underlying data. We just remove/add column definitions to the object used as the "columns" attribute.

There is no need to scroll, the problem appears immediately.

**Comment by PascalLeMerrer** [comment]
Here is [an example](https://gist.github.com/PascalLeMerrer/64308c511e265788bf01fa3f08c209c6) of this issue.
I took the index.html in the test folder and added a "hide column" button which replaces the content of the gridcols attribute, with a new list.
The new list has the same content than the initial one, except the third item was removed (the third item being 

        {
            label: 'name',
            field: "name1",
            width: 120,
            fixed: true
        }
)

After this, the display in the first column is broken. It does not reproduce the exact behavior I observed, but it's likely to be the same problem.

**Comment by crisward** [comment]
Here

https://github.com/crisward/riot-grid2/blob/master/src/grid2.tag#L113

I take a copy of the columns, for comparison on update. However columns is an array, so the copy is a reference.

So if you're mutating the columns array, the `calcPos` method may not be being re-rerun. Try creating an array copy and passing that in (presuming you are mutating).

eg.

```javascript
var columns = [
    {label:'#',field:'id',width:50,fixed:true,class:'identifier'},
    {label:'name',field:"name1",width:120,fixed:true,class:'name primary'},
    {label:'name2',field:"name2",width:120,class:['name','secondary']},
    {label:"popularity",field:"popularity",width:200,tag:"image-cell"}
]

// removing name row as a new array
columns = columns.filter(function(row) {
	return row.label != "name"
});
```

This is only a guess I've not had chance to check this.

**Comment by PascalLeMerrer** [comment]
Unless my understanding is incorrect, I'm already doing this (both in the [modified test file](https://gist.github.com/PascalLeMerrer/64308c511e265788bf01fa3f08c209c6) and in my real app - although in a much cleaner way in my app :) )

In fact, if you just alter the columns array, instead of recreating it, nothing happens in the grid.

**Comment by crisward** [comment]
Sorry, just guessing without looking, was at work at the time...

Just tried your example and as you said the columns don't render correctly. It looks like the correct tag is being used (image tag) but it's src attribute is blank. I'll see if I can write a failing test and make it pass.

**Comment by crisward** [comment]
Found the issue, the cell cache needed reseting when columns are changed.
It does this now. Took a bit of digging, push a new version to npm @3.0.2

**Comment by crisward** [comment]
Close this once you've had chance to confirm.

**Comment by PascalLeMerrer** [comment]
It works!

Thanks a lot Cris!
