### ISSUE TITLE
MouseWheel scrolling is really slow (Firefox performance?)

### ISSUE THREAD

**Issue by PascalLeMerrer** [crisward/riot-grid2#23]
Hi Cris

When using a mouse wheel to scroll on a large array, the scrolling is really slow, making the mouse wheel quite useless.

It could be fixed quite easily: in the scrolling function, just multiply deltaY by a constant integer when the event is of type WheelEvent.

Do you agree with this?

**Comment by crisward** [comment]
It seems fine in the demo on my mac book.
 
It could be a variation in how the mousewheel event is handled.

* Does the demo work ok - http://crisward.github.io/riot-grid2/ ?
* What browser / OS are you using?
* Does it vary between browsers?

**Comment by PascalLeMerrer** [comment]
The problem seems to be specific to Firefox.
I reproduced it using your demo with FF on windows, OSX and Linux, on several computers.
It works well with Edge, Safari and Chrome.

**Comment by crisward** [comment]
Thanks for identifying this. I'm not sure if it's a scroll 'speed' issue. It seems more like a rendering performance issue (I've only tested on my macbook). I'm probably causing more repaints on firefox. I'm less familiar with firefox's dev tools. Hopefully they have some kind of frame rate tool I can use to identify / optimise this.

Thanks.

**Comment by crisward** [comment]
2 years later and firefox perf seems fine to me. Maybe it's my new iMac, maybe it's the inevitable progress of browsers. Who knows? Closing, and thanks again for your feedback.
