### ISSUE TITLE
Resizeable Columns

### ISSUE THREAD

**Issue by tooolbox** [crisward/riot-grid2#24]
Great component!  Just what I was looking for and I think very needed in the Riot ecosystem.

Any progress on the resize-able columns feature, or timetable for this?

**Comment by crisward** [comment]
I've haven't touched this component in a few months. I created it a for a couple of projects I was working on in riot, and they don't need all the features I eventually want to add.

There is also an open issue for custom tags in headers. I think adding that could make resizable columns possible too. So I should prioritise that.

As for timescales... sorry no idea, never know when I'm next going to get chance to do some open sourcery... Though I'll be sure to update this issue when it's there.

**Comment by crisward** [comment]
The project I developed this for doesn't need this feature, so I'm closing this for now. Feel free to fork and add features. I may even accept a pull request if it's well tested.
