### ISSUE TITLE
Compatibility with latest version of Riot

### ISSUE THREAD

**Issue by ronen** [crisward/riot-grid2#3]
Hi,

I just tried this out, and found that it failed, lots of errors along the lines of `Cannot read property  'scrollTop' of undefined in GRID2`.

Some quick investigation shows that it works for me with Riot 2.4.1 (same as your demo) but not with the latest release (2.6.3) nor with 3.0.0-alpha.10 (which is what I'm using in my project, aiming towards the future).

I haven't (yet) looked any deeper into what's going on.  I may try to track it down & PR, but if you beat me to it that'd be cool :)

Thanks

**Comment by crisward** [comment]
I'll maybe take a look later. This was done for a specific project, which I've locked to an older version of riot for the sake of stability. Not tried Riot 3.0 yet as I'm in no rush to build on alpha releases, though I am sure riot 3.0 should really help with their new riot-tag / data-is attribute which takes a dynamic value.

**Comment by crisward** [comment]
Updated the repo and demo to riot 2.6.3 and it worked fine.

I'll look into riot 3.0 when it has been finished. Hopefully the changes will be minor and backward compatible.

**Comment by ronen** [comment]
@crisward Thanks for looking into it.  Dunno why 2.6.3 didn't seem to work for me, I must have done something dopey like not properly reloading/restarting when I tried it.  The riot devs claim that the 3.0 alpha is pretty stable (see https://github.com/riot/riot/issues/1694#issuecomment-246140828), and the new release seems pretty imminent, which is why I'm using it for my new project.

But given that grid2 works in 2.6.3 the problem is just the breaking changes in 3.0 :)  I took a look at the grid2 code; there are a couple of 3.0 things that I know affect grid2: (From riot/riot#1694):

> - [x] use the ref attribute instead of names and ids riot/riot#1185  
> - [x] avoid to inherit properties from the parent in loops of custom children tags riot/riot#1697

Also `jade` has been renamed `pug`

I've made a [`riot3` branch in my fork](https://github.com/ronen/riot-grid2/tree/riot3) conforming to the above changes.   That gets it working.  (And yes it _is_ blazingly fast!  Love it!!)   But there are still two tests that fail, which I haven't figured out yet:

```
TOTAL: 2 FAILED, 10 SUCCESS

1) should call onclick on row when cell is clicked
     grid2
     expected false to be true
2) should pass events through overlay to grid below
     grid2
     expected false to be true
```

If you have any ideas....  (For my project I actually don't currently need to click cells so that's not going to slow me down, so I might just leave it at this for now.)  

Thanks again for making this!

**Comment by ronen** [comment]
FYI I added a few more commits to my branch, in particular cleaning up javascript errors when the tag is first being built (before the `"mount"` callback gets called) due to uninitialized values.

And I looked a little more into those click/event errors.  Turns out that `onclick` _is_ being called, and events _are_ being passed through -- the problem is that the spy is being called two or three times, rather than once as expected.  Haven't yet tracked down why.

**Comment by PascalLeMerrer** [comment]
Hi

RiotJS 3.0 is out. Can we expect a new release of this great component?

**Comment by crisward** [comment]
Yes... it should in theory work quicker on riot 3 and I should be able to strip out a bit of code.
I'll probably release a version on npm as version 3.0.0, to allow users who are stuck on 2.* can still use the older version.

I'll try and update it over the weekend.

**Comment by crisward** [comment]
I've pushed a new version here. I'll push a version to npm tomorrow.

**Comment by crisward** [comment]
Thats been pushed to npm `riot-grid2@3.0.0`

https://www.npmjs.com/package/riot-grid2
