### ISSUE TITLE
Issue on iOS

### ISSUE THREAD

**Issue by fabien** [crisward/riot-grid2#5]
While scrolling through the example on an iPad Pro, the page is reloaded after around 200 rows down. A message pops up that there's been an error on the page.

**Comment by crisward** [comment]
Thanks for the feedback.

The demo has 100,000 rows. I **think** the ipad may restrict the memory usage and dump the tab if the memory usage is exceeded. When I get chance I'll modify the demo to allow you to choose a row count. In real world use, you'd probably download your data in smaller batches than 3 million fields at a time.

**Comment by crisward** [comment]
I've just checked, and in chrome it the tab uses around 550mb of ram for the demo. I'm guessing that may be quite a lot for the ipad. Also safari may use more.

**Comment by crisward** [comment]
I've reduced the number of rows in the demo to 10,000. Seems to have stopped it crashing.
This is probably something you'll need to manage within your app, so I'll close this for now. May look to create a progressive data loading system in the future which could solve memory related issues with very large grids.
