### ISSUE TITLE
cannot detect hover in custom cell

### ISSUE THREAD

**Issue by PascalLeMerrer** [crisward/riot-grid2#6]
Hi

I would like to add a tooltip to a progress bar like the one you used in the demo.
But hover seems to be ignored in custom tags when they are used to render cells.

By example something as simple as adding a title to a cell tag like this one from your demo does not display anything when the mouse is above:

```
        <image>
            <img riot-src="{opts.val}" title="some title" style="margin:-10px -5px" />
        </image>
```
Do you have any idea of how I could achieve this?

**Comment by crisward** [comment]
The grid uses a bit of a hack to enable scrolling, if you right click and inspect element, you'll see what I mean. It uses a Div with a class of `scrollArea` which intercepts the scrolling and passes it into elements below. This was the best way of keeping the various fixed panels in alignment.

To enable the click events I'm pushing through events from the top level through to the divs below. https://github.com/crisward/riot-grid2/blob/master/src/grid2.tag#L138

It should be possible to do the same on `mouseenter`, `mouseleave` etc by adding them to the on mount https://github.com/crisward/riot-grid2/blob/master/src/grid2.tag#L84

Or I'll see if I can add it at some point, though it may take me a few days to get onto it.

**Comment by crisward** [comment]
Also if you don't need lots of columns, https://github.com/crisward/riot-grid doesn't use any such hacks.

**Comment by PascalLeMerrer** [comment]
I have to display 60 columns, so the first version of riot-grid is not an option.

**Comment by crisward** [comment]
Yes, I had that problem, hence the two versions....

I'll update here when I have a solution.

**Comment by crisward** [comment]
I've tried pushing though more events. This works with `mouseup` / `mousedown`. However to push through a hover, you need a `mouseenter`, `mouseleave` event combination. This isn't really possible with the current setup as the whole grid is covered by a div to detect the scroll. You only `enter` this once when going over the grid.

I've added a push through for `movemove` This should get fired on the tag directly under your mouse. So you may able to detect this and show a custom tooltip.

Ideally I could do with finding a better way to listen in on the scroll event. This component was created for a project which needed to display lots of data, but not necessarily interact with it too much. I'd be happy to take any suggestions on this. I'll have a think myself and see if I can come up with something...

**Comment by crisward** [comment]
This should now be possible as I've reworked the scroll system.
Not pushed to npm yet as I have a few issues to solve with the scrollbars not receiving events and I've lost the nice scroll bounce on mobile...
